In [39]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [40]:
df=pd.read_csv('Dataset.csv')

In [41]:
df['sales'] = pd.to_numeric(df['sales'].astype(str).str.replace(',', ''), errors='coerce')
df['profit'] = pd.to_numeric(df['profit'], errors='coerce')

In [42]:
# Date fields convert to datetime format
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce')

df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df['order_dayofweek'] = df['order_date'].dt.dayofweek

df['shipping_days'] = (df['ship_date'] - df['order_date']).dt.days

print("Date features extracted successfully!")
df[['order_date', 'order_year', 'order_month', 'shipping_days']].head()

Date features extracted successfully!

  order_date  order_year  order_month  shipping_days
0 2011-01-01      2011.0          1.0          151.0
1 2011-01-01      2011.0          1.0          212.0
2 2011-01-01      2011.0          1.0          120.0
3 2011-01-01      2011.0          1.0          120.0
4 2011-01-01      2011.0          1.0          212.0

In [44]:
df['unit_price'] = df['sales'] / df['quantity']
df['profit_margin'] = df['profit'] / df['sales']
df.fillna(0, inplace=True)

In [45]:
# Categorical Columns
categorical_cols = ['ship_mode', 'segment', 'market', 'region', 'category', 'sub_category', 'order_priority']

label_encoder = LabelEncoder()

for col in categorical_cols:
    df[col + '_encoded'] = label_encoder.fit_transform(df[col].astype(str))

print("Categorical encoding completed!")

Categorical encoding completed!

In [46]:
target_variable='profit'

drop_columns=['order_id', 'order_date', 'ship_date', 'customer_name', 'state', 'country','product_id', 'product_name'] +categorical_cols
ml_df = df.drop(columns=drop_columns)

print("Final ML-Ready Dataset Shape:", ml_df.shape)
print("Selected Target Variable:", target_variable)
ml_df.head()

Final ML-Ready Dataset Shape: (51325, 20)
Selected Target Variable: profit

,sales,quantity,discount,profit,shipping_cost,year,order_year,order_month,order_day,order_dayofweek,shipping_days,unit_price,profit_margin,ship_mode_encoded,segment_encoded,market_encoded,region_encoded,category_encoded,sub_category_encoded,order_priority_encoded
0,408,2,0.0,106.140,35.46,2011,2011.0,1.0,1.0,5.0,151.0,204.0,0.260147,3,0,1,0,1,14,3
1,120,3,0.1,36.036,9.72,2011,2011.0,1.0,1.0,5.0,212.0,40.0,0.300300,3,0,0,9,1,15,3
2,66,4,0.0,29.640,8.17,2011,2011.0,1.0,1.0,5.0,120.0,16.5,0.449091,2,0,3,5,1,14,1
3,45,3,0.5,-26.055,4.82,2011,2011.0,1.0,1.0,5.0,120.0,15.0,-0.579000,2,2,4,7,1,12,1
4,114,5,0.1,37.770,4.70,2011,2011.0,1.0,1.0,5.0,212.0,22.8,0.331316,3,0,0,9,0,9,3

In [47]:
ml_df.to_csv('ml_ready_dataset.csv', index=False)

from google.colab import files
files.download('ml_ready_dataset.csv')